//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:57:07 AM IST 
//


package com.codehawk.jaxb.scheduleservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AGENCY_SCHEDULE_LIST_REQUEST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AGENCY_SCHEDULE_LIST_REQUEST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AGENCY_ID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="AGENCY_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AGENCY_SCHEDULE_LIST_REQUEST", propOrder = {
    "agencyid",
    "agencyname"
})
public class AGENCYSCHEDULELISTREQUEST {

    @XmlElement(name = "AGENCY_ID", required = true)
    protected String agencyid;
    @XmlElement(name = "AGENCY_NAME", required = true)
    protected String agencyname;

    /**
     * Gets the value of the agencyid property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGENCYID() {
        return agencyid;
    }

    /**
     * Sets the value of the agencyid property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGENCYID(String value) {
        this.agencyid = value;
    }

    /**
     * Gets the value of the agencyname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGENCYNAME() {
        return agencyname;
    }

    /**
     * Sets the value of the agencyname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGENCYNAME(String value) {
        this.agencyname = value;
    }

}
