//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:57:07 AM IST 
//


package com.codehawk.jaxb.scheduleservice;

import java.math.BigDecimal;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AGENCY_SCHEDULE complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AGENCY_SCHEDULE">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AGENCY_SCHEDULE_ID" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="AGENGY_SCHEDULE_NAME" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AGENCY_SCHEDULE", propOrder = {
    "agencyscheduleid",
    "agengyschedulename"
})
public class AGENCYSCHEDULE {

    @XmlElement(name = "AGENCY_SCHEDULE_ID", required = true)
    protected BigDecimal agencyscheduleid;
    @XmlElement(name = "AGENGY_SCHEDULE_NAME", required = true)
    protected String agengyschedulename;

    /**
     * Gets the value of the agencyscheduleid property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getAGENCYSCHEDULEID() {
        return agencyscheduleid;
    }

    /**
     * Sets the value of the agencyscheduleid property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setAGENCYSCHEDULEID(BigDecimal value) {
        this.agencyscheduleid = value;
    }

    /**
     * Gets the value of the agengyschedulename property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAGENGYSCHEDULENAME() {
        return agengyschedulename;
    }

    /**
     * Sets the value of the agengyschedulename property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAGENGYSCHEDULENAME(String value) {
        this.agengyschedulename = value;
    }

}
