//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:57:07 AM IST 
//


package com.codehawk.jaxb.scheduleservice;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for AGENCY_SCHEDULE_LIST complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AGENCY_SCHEDULE_LIST">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="AGENCY_SCHEDULE" type="{}AGENCY_SCHEDULE"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AGENCY_SCHEDULE_LIST", propOrder = {
    "agencyschedule"
})
public class AGENCYSCHEDULELIST {

    @XmlElement(name = "AGENCY_SCHEDULE", required = true)
    protected AGENCYSCHEDULE agencyschedule;

    /**
     * Gets the value of the agencyschedule property.
     * 
     * @return
     *     possible object is
     *     {@link AGENCYSCHEDULE }
     *     
     */
    public AGENCYSCHEDULE getAGENCYSCHEDULE() {
        return agencyschedule;
    }

    /**
     * Sets the value of the agencyschedule property.
     * 
     * @param value
     *     allowed object is
     *     {@link AGENCYSCHEDULE }
     *     
     */
    public void setAGENCYSCHEDULE(AGENCYSCHEDULE value) {
        this.agencyschedule = value;
    }

}
