//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.3 in JDK 1.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.10.03 at 10:57:07 AM IST 
//


package com.codehawk.jaxb.scheduleservice;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.codehawk.jaxb.scheduleservice package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.codehawk.jaxb.scheduleservice
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link POLICYBORDEREAUIMPORTSCHEDULELISTREQUEST }
     * 
     */
    public POLICYBORDEREAUIMPORTSCHEDULELISTREQUEST createPOLICYBORDEREAUIMPORTSCHEDULELISTREQUEST() {
        return new POLICYBORDEREAUIMPORTSCHEDULELISTREQUEST();
    }

    /**
     * Create an instance of {@link AGENCYSCHEDULELISTRESPONSE }
     * 
     */
    public AGENCYSCHEDULELISTRESPONSE createAGENCYSCHEDULELISTRESPONSE() {
        return new AGENCYSCHEDULELISTRESPONSE();
    }

    /**
     * Create an instance of {@link POLICYBORDEREAUIMPORTSCHEDULELISTRESPONSE }
     * 
     */
    public POLICYBORDEREAUIMPORTSCHEDULELISTRESPONSE createPOLICYBORDEREAUIMPORTSCHEDULELISTRESPONSE() {
        return new POLICYBORDEREAUIMPORTSCHEDULELISTRESPONSE();
    }

    /**
     * Create an instance of {@link AGENCYSCHEDULELISTREQUEST }
     * 
     */
    public AGENCYSCHEDULELISTREQUEST createAGENCYSCHEDULELISTREQUEST() {
        return new AGENCYSCHEDULELISTREQUEST();
    }

    /**
     * Create an instance of {@link POLICYBORDEREAUSCHEDULEDETAILLIST }
     * 
     */
    public POLICYBORDEREAUSCHEDULEDETAILLIST createPOLICYBORDEREAUSCHEDULEDETAILLIST() {
        return new POLICYBORDEREAUSCHEDULEDETAILLIST();
    }

    /**
     * Create an instance of {@link AGENCYBORDEREAUIMPORTSCHEDULELISTRESPONSE }
     * 
     */
    public AGENCYBORDEREAUIMPORTSCHEDULELISTRESPONSE createAGENCYBORDEREAUIMPORTSCHEDULELISTRESPONSE() {
        return new AGENCYBORDEREAUIMPORTSCHEDULELISTRESPONSE();
    }

    /**
     * Create an instance of {@link EDITAGENCYSCHEDULEREQUEST }
     * 
     */
    public EDITAGENCYSCHEDULEREQUEST createEDITAGENCYSCHEDULEREQUEST() {
        return new EDITAGENCYSCHEDULEREQUEST();
    }

    /**
     * Create an instance of {@link EDITPOLICYSCHEDULEREQUEST }
     * 
     */
    public EDITPOLICYSCHEDULEREQUEST createEDITPOLICYSCHEDULEREQUEST() {
        return new EDITPOLICYSCHEDULEREQUEST();
    }

    /**
     * Create an instance of {@link AGENCYBORDEREAUIMPORTSCHEDULE }
     * 
     */
    public AGENCYBORDEREAUIMPORTSCHEDULE createAGENCYBORDEREAUIMPORTSCHEDULE() {
        return new AGENCYBORDEREAUIMPORTSCHEDULE();
    }

    /**
     * Create an instance of {@link EDITAGENCYSCHEDULERESPONSE }
     * 
     */
    public EDITAGENCYSCHEDULERESPONSE createEDITAGENCYSCHEDULERESPONSE() {
        return new EDITAGENCYSCHEDULERESPONSE();
    }

    /**
     * Create an instance of {@link AGENCYBORDEREAUIMPORTSCHEDULELIST }
     * 
     */
    public AGENCYBORDEREAUIMPORTSCHEDULELIST createAGENCYBORDEREAUIMPORTSCHEDULELIST() {
        return new AGENCYBORDEREAUIMPORTSCHEDULELIST();
    }

    /**
     * Create an instance of {@link POLICYBORDEREAUSCHEDULEDETAIL }
     * 
     */
    public POLICYBORDEREAUSCHEDULEDETAIL createPOLICYBORDEREAUSCHEDULEDETAIL() {
        return new POLICYBORDEREAUSCHEDULEDETAIL();
    }

    /**
     * Create an instance of {@link ADDAGENCYSCHEDULEDEFINITIONREQUEST }
     * 
     */
    public ADDAGENCYSCHEDULEDEFINITIONREQUEST createADDAGENCYSCHEDULEDEFINITIONREQUEST() {
        return new ADDAGENCYSCHEDULEDEFINITIONREQUEST();
    }

    /**
     * Create an instance of {@link EDITPOLICYSCHEDULERESPONSE }
     * 
     */
    public EDITPOLICYSCHEDULERESPONSE createEDITPOLICYSCHEDULERESPONSE() {
        return new EDITPOLICYSCHEDULERESPONSE();
    }

    /**
     * Create an instance of {@link AGENCYSCHEDULELIST }
     * 
     */
    public AGENCYSCHEDULELIST createAGENCYSCHEDULELIST() {
        return new AGENCYSCHEDULELIST();
    }

    /**
     * Create an instance of {@link ADDAGENCYSCHEDULEDEFINITIONRESPONSE }
     * 
     */
    public ADDAGENCYSCHEDULEDEFINITIONRESPONSE createADDAGENCYSCHEDULEDEFINITIONRESPONSE() {
        return new ADDAGENCYSCHEDULEDEFINITIONRESPONSE();
    }

    /**
     * Create an instance of {@link AGENCYBORDEREAUIMPORTSCHEDULELISTREQUEST }
     * 
     */
    public AGENCYBORDEREAUIMPORTSCHEDULELISTREQUEST createAGENCYBORDEREAUIMPORTSCHEDULELISTREQUEST() {
        return new AGENCYBORDEREAUIMPORTSCHEDULELISTREQUEST();
    }

    /**
     * Create an instance of {@link AGENCYSCHEDULE }
     * 
     */
    public AGENCYSCHEDULE createAGENCYSCHEDULE() {
        return new AGENCYSCHEDULE();
    }

}
